packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true

overrides:
  electron-to-chromium: 1.5.380

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tarojs/binding"
  - "@tarojs/cli"
  - core-js
  - core-js-pure
  - esbuild
