export default defineAppConfig({
  pages: [
    "pages/index/index",
    "pages/genshin/index",
    "pages/TurtleSoup/index",
    "pages/HanDou/index",
    "pages/Sudoku/index",
    "pages/Wish/index",
    "pages/Pokemon/index",
    "pages/ScriptRecord/index",
    "pages/ScriptRecordConfig/index",
    "pages/QrCode/index",
    "pages/Mbti/index",
    "pages/CardExchangeMarket/index",
    "pages/CardExchangeMine/index",
    "pages/About/index",
  ],
  window: {
    backgroundTextStyle: "light",
    backgroundColor: "#30231d",
    backgroundColorTop: "#30231d",
    backgroundColorBottom: "#30231d",
    navigationBarBackgroundColor: "#30231d",
    navigationBarTextStyle: "white",
  },
});
