// cspell:disable

/** 池子枚举 */
export enum GachaTypeKey {
  ROLE = "ROLE",
  WEAPON = "WEAPON",
  NORMAL = "NORMAL",
  MIX = "MIX",
}
export const GachaType = {
  [GachaTypeKey.ROLE]: {
    label: "角色",
    code: "301",
  },
  [GachaTypeKey.WEAPON]: {
    label: "武器",
    code: "302",
  },
  [GachaTypeKey.MIX]: {
    label: "集录",
    code: "500",
  },
  [GachaTypeKey.NORMAL]: {
    label: "常驻",
    code: "200",
  },
};

/** 角色列表 */
export const roleList = [
  { name: "莫娜", englishName: "Mona", version: "1.0", isNormal: true },
  {
    name: "琴",
    englishName: "Qin",
    version: "1.0",
    isNormal: true,
  },
  { name: "七七", englishName: "Qiqi", version: "1.0", isNormal: true },
  { name: "刻晴", englishName: "Keqing", version: "1.0", isNormal: true },
  { name: "迪卢克", englishName: "Diluc", version: "1.0", isNormal: true },

  { name: "温迪", englishName: "Venti", version: "1.0" },
  { name: "可莉", englishName: "Klee", version: "1.0" },
  { name: "达达利亚", englishName: "Tartaglia", version: "1.1" },
  { name: "钟离", englishName: "Zhongli", version: "1.1" },
  { name: "阿贝多", englishName: "Albedo", version: "1.2" },
  { name: "甘雨", englishName: "Ganyu", version: "1.2" },
  { name: "魈", englishName: "Xiao", version: "1.3" },
  {
    name: "胡桃",
    englishName: "Hutao",
    version: "1.3",
  },
  { name: "优菈", englishName: "Eula", version: "1.5" },
  { name: "万叶", englishName: "Kazuha", version: "1.6" },

  { name: "神里绫华", englishName: "Ayaka", version: "2.0" },
  { name: "宵宫", englishName: "Yoimiya", version: "2.0" },
  {
    name: "雷电将军",
    englishName: "Shougun",
    version: "2.1",
  },
  {
    name: "珊瑚宫心海",
    englishName: "Kokomi",
    version: "2.1",
  },
  {
    name: "荒泷一斗",
    englishName: "Itto",
    version: "2.3",
  },
  { name: "申鹤", englishName: "Shenhe", version: "2.4" },
  {
    name: "八重神子",
    englishName: "Yae",
    version: "2.5",
  },
  {
    name: "神里绫人",
    englishName: "Ayato",
    version: "2.6",
  },
  { name: "夜兰", englishName: "Yelan", version: "2.7" },

  { name: "提纳里", englishName: "Tighnari", version: "3.0", isNormal: true },
  { name: "妮露", englishName: "Nilou", version: "3.1" },
  { name: "赛诺", englishName: "Cyno", version: "3.1" },
  { name: "纳西妲", englishName: "Nahida", version: "3.2" },
  { name: "流浪者", englishName: "Wanderer", version: "3.3" },
  {
    name: "艾尔海森",
    englishName: "Alhatham",
    version: "3.4",
  },
  { name: "迪希雅", englishName: "Dehya", version: "3.5", isNormal: true },
  {
    name: "白术",
    englishName: "Baizhuer",
    version: "3.6",
  },

  { name: "林尼", englishName: "Liney", version: "4.0" },
  { name: "莱欧斯利", englishName: "Wriothesley", version: "4.1" },
  { name: "那维莱特", englishName: "Neuvillette", version: "4.1" },
  { name: "芙宁娜", englishName: "Furina", version: "4.2" },
  { name: "娜维娅", englishName: "Navia", version: "4.3" },
  {
    name: "闲云",
    englishName: "Liuyun",
    version: "4.4",
  },
  { name: "千织", englishName: "Chiori", version: "4.5" },
  { name: "阿蕾奇诺", englishName: "Arlecchino", version: "4.6" },
  { name: "克洛琳德", englishName: "Clorinde", version: "4.7" },
  { name: "希格雯", englishName: "Sigewinne", version: "4.7" },
  { name: "艾梅莉埃", englishName: "Emilie", version: "4.8" },

  { name: "玛拉妮", englishName: "Mualani", version: "5.0" },
  { name: "基尼奇", englishName: "Kinich", version: "5.0" },
  { name: "希诺宁", englishName: "Xilonen", version: "5.1" },
  { name: "恰斯卡", englishName: "Chasca", version: "5.2" },
  { name: "茜特菈莉", englishName: "Citlali", version: "5.3" },
  { name: "玛薇卡", englishName: "Mavuika", version: "5.3" },
  { name: "梦见月瑞希", englishName: "Mizuki", version: "5.4", isNormal: true },
  { name: "瓦雷莎", englishName: "Varesa", version: "5.5" },
  { name: "爱可菲", englishName: "Escoffier", version: "5.6" },
  { name: "丝柯克", englishName: "SkirkNew", version: "5.7" },
  { name: "伊涅芙", englishName: "Ineffa", version: "5.8" },

  { name: "菈乌玛", englishName: "Lauma", version: "6.0" },
  { name: "菲林斯", englishName: "Flins", version: "6.0" },
  { name: "奈芙尔", englishName: "Nefer", version: "6.1" },
  {
    name: "杜林",
    englishName: "Durin",
    version: "6.2",
  },
  {
    name: "哥伦比娅",
    englishName: "Columbina",
    version: "6.3",
  },
  {
    name: "兹白",
    englishName: "Zibai",
    version: "6.4",
  },
  {
    name: "法尔伽",
    englishName: "Varka",
    version: "6.5",
  },
  {
    name: "莉奈娅",
    englishName: "Linnea",
    version: "6.6",
  },
  {
    name: "尼可",
    englishName: "Nicole",
    version: "6.7",
  },
  {
    name: "洛恩",
    englishName: "Lohen",
    version: "6.8",
  },
  {
    name: "桑多涅",
    englishName: "MarionetteNew",
    version: "6.8",
  },
  {
    name: "奥黛塔",
    englishName: "Odette",
    version: "7.0",
  },
  { name: "薇斯纳", englishName: "Vesna", version: "7.1" },
  { name: "沃雅妮莎", englishName: "Vodyanitsa", version: "7.1" },
];

// 按登场顺序排列；englishName 用于拼接 UI_AvatarIcon 头像资源地址。
export const fourStarRoleList = [
  { name: "安柏", englishName: "Ambor" },
  { name: "凯亚", englishName: "Kaeya" },
  { name: "丽莎", englishName: "Lisa" },
  { name: "芭芭拉", englishName: "Barbara" },
  { name: "雷泽", englishName: "Razor" },
  { name: "香菱", englishName: "Xiangling" },
  { name: "北斗", englishName: "Beidou" },
  { name: "行秋", englishName: "Xingqiu" },
  { name: "凝光", englishName: "Ningguang" },
  { name: "菲谢尔", englishName: "Fischl" },
  { name: "班尼特", englishName: "Bennett" },
  { name: "诺艾尔", englishName: "Noel" },
  { name: "重云", englishName: "Chongyun" },
  { name: "砂糖", englishName: "Sucrose" },
  { name: "迪奥娜", englishName: "Diona" },
  { name: "辛焱", englishName: "Xinyan" },
  { name: "罗莎莉亚", englishName: "Rosaria" },
  { name: "烟绯", englishName: "Feiyan" },
  { name: "早柚", englishName: "Sayu" },
  { name: "九条裟罗", englishName: "Sara" },
  { name: "托马", englishName: "Tohma" },
  { name: "五郎", englishName: "Gorou" },
  { name: "云堇", englishName: "Yunjin" },
  { name: "久岐忍", englishName: "Shinobu" },
  { name: "鹿野院平藏", englishName: "Heizo" },
  { name: "柯莱", englishName: "Collei" },
  { name: "多莉", englishName: "Dori" },
  { name: "坎蒂丝", englishName: "Candace" },
  { name: "莱依拉", englishName: "Layla" },
  { name: "珐露珊", englishName: "Faruzan" },
  { name: "瑶瑶", englishName: "Yaoyao" },
  { name: "米卡", englishName: "Mika" },
  { name: "卡维", englishName: "Kaveh" },
  { name: "绮良良", englishName: "Momoka" },
  { name: "琳妮特", englishName: "Linette" },
  { name: "菲米尼", englishName: "Freminet" },
  { name: "夏洛蒂", englishName: "Charlotte" },
  { name: "夏沃蕾", englishName: "Chevreuse" },
  { name: "嘉明", englishName: "Gaming" },
  { name: "赛索斯", englishName: "Sethos" },
  { name: "卡齐娜", englishName: "Kachina" },
  { name: "欧洛伦", englishName: "Olorun" },
  { name: "蓝砚", englishName: "Lanyan" },
  { name: "伊安珊", englishName: "Iansan" },
  { name: "伊法", englishName: "Ifa" },
  { name: "塔利雅", englishName: "Dahlia" },
  { name: "爱诺", englishName: "Aino" },
  { name: "雅珂达", englishName: "Jahoda" },
  { name: "叶洛亚", englishName: "Illuga" },
  { name: "布伦妮", englishName: "Prune" },
  { name: "阿罗夏", englishName: "Alyosha" },
];
